name: Matrix Example

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
      - name: Print Python Version
        run: echo "Running on Python ${{ matrix.python-version }}"