name: Testing Workflow Variables

on:
  workflow_dispatch # for manual trigger

env:
  cloud: google-cloud

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: Greeting guest
        env:
          First_Name: Pradyumna
        run: echo "$Greeting $First_Name, are you using $cloud!"
        
